"""create location and forecast_observation tables

Revision ID: 4977841176ab
Revises:
Create Date: 2026-04-29 20:28:29.332405

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4977841176ab"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "location",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("latitude", "longitude", name="uq_location_lat_lon"),
    )
    op.create_table(
        "forecast_observation",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(), nullable=False),
        sa.Column("forecast_for", sa.DateTime(), nullable=False),
        sa.Column("temperature", sa.Float(), nullable=False),
        sa.Column("temperature_unit", sa.Enum("C", "F", name="temperatureunit"), nullable=False),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["location.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_forecast_observation_location_id"),
        "forecast_observation",
        ["location_id"],
        unique=False,
    )
    op.create_index(
        "ix_observation_location_forecast_for",
        "forecast_observation",
        ["location_id", "forecast_for"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_observation_location_forecast_for", table_name="forecast_observation")
    op.drop_index(op.f("ix_forecast_observation_location_id"), table_name="forecast_observation")
    op.drop_table("forecast_observation")
    op.drop_table("location")
    # ### end Alembic commands ###
